import io
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas

class NumberedCanvas(canvas.Canvas):
    """Canvas that performs two-pass rendering to dynamically compute and write total page counts in footer."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        
        # Draw Header rule and text on all pages
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(colors.HexColor('#1a365d'))
        self.drawString(40, 755, "AI CLINICAL DECISION SUPPORT SYSTEM")
        
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor('#4a5568'))
        self.drawRightString(572, 755, "HEART DISEASE ASSESSMENT REPORT")
        
        self.setStrokeColor(colors.HexColor('#cbd5e0'))
        self.setLineWidth(0.5)
        self.line(40, 748, 572, 748)
        
        # Draw Footer rule and text on all pages
        self.line(40, 48, 572, 48)
        self.setFont("Helvetica", 8)
        self.drawString(40, 36, "Generated by: Explainable AI Healthcare Analytics Platform")
        
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        self.drawString(320, 36, f"Compiled: {timestamp}")
        
        self.drawRightString(572, 36, f"Page {self._pageNumber} of {page_count}")
        self.restoreState()


def generate_pdf_report(
    patient_raw_dict, 
    model_predictions, 
    model_probabilities, 
    model_confidences, 
    ensemble_label, 
    pos_votes, 
    total_votes, 
    risk_score, 
    risk_category, 
    risk_desc, 
    rules, 
    df_pos, 
    df_neg, 
    detected_warnings, 
    recs, 
    warnings
):
    """Generates a professional clinical PDF report for the active patient and returns raw PDF bytes."""
    buffer = io.BytesIO()
    
    # 40pt margins = 0.55 inch. Page printable area width = 612 - 80 = 532.
    doc = SimpleDocTemplate(
        buffer, 
        pagesize=letter, 
        leftMargin=40, 
        rightMargin=40, 
        topMargin=55, 
        bottomMargin=60
    )
    
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=20,
        leading=24,
        textColor=colors.HexColor('#1a365d'),
        spaceAfter=15
    )
    
    h1_style = ParagraphStyle(
        'Heading1_Custom',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        textColor=colors.HexColor('#2b6cb0'),
        spaceBefore=15,
        spaceAfter=8,
        keepWithNext=True
    )
    
    body_style = ParagraphStyle(
        'Body_Custom',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=13,
        textColor=colors.HexColor('#2d3748')
    )
    
    body_bold_style = ParagraphStyle(
        'Body_Bold_Custom',
        parent=body_style,
        fontName='Helvetica-Bold'
    )
    
    table_header_style = ParagraphStyle(
        'TableHeader',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=9,
        leading=12,
        textColor=colors.white
    )
    
    table_cell_style = ParagraphStyle(
        'TableCell',
        parent=body_style,
        fontSize=8.5,
        leading=11
    )
    
    table_cell_bold_style = ParagraphStyle(
        'TableCellBold',
        parent=table_cell_style,
        fontName='Helvetica-Bold'
    )

    story = []
    
    # Title
    story.append(Paragraph("Patient Health & Risk Assessment Report", title_style))
    story.append(Spacer(1, 10))
    
    # -------------------- 1. PATIENT INFORMATION --------------------
    story.append(Paragraph("1. Patient Clinical Metrics", h1_style))
    
    # Setup Patient Metrics Grid (4 columns table: label, value, label, value)
    pat_keys = list(patient_raw_dict.keys())
    pat_values = list(patient_raw_dict.values())
    
    grid_data = []
    for i in range(0, len(pat_keys), 2):
        row = []
        # Item 1
        row.append(Paragraph(pat_keys[i], table_cell_bold_style))
        row.append(Paragraph(str(pat_values[i]), table_cell_style))
        # Item 2 (if index doesn't exceed length)
        if i + 1 < len(pat_keys):
            row.append(Paragraph(pat_keys[i+1], table_cell_bold_style))
            row.append(Paragraph(str(pat_values[i+1]), table_cell_style))
        else:
            row.append(Paragraph("", table_cell_style))
            row.append(Paragraph("", table_cell_style))
        grid_data.append(row)
        
    t_patient = Table(grid_data, colWidths=[140, 126, 140, 126])
    t_patient.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (0,-1), colors.HexColor('#edf2f7')),
        ('BACKGROUND', (2,0), (2,-1), colors.HexColor('#edf2f7')),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 5),
        ('TOPPADDING', (0,0), (-1,-1), 5),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
    ]))
    story.append(t_patient)
    story.append(Spacer(1, 12))
    
    # -------------------- 2. ENSEMBLE RESULTS --------------------
    story.append(Paragraph("2. Multi-Model Inference & Consensus Results", h1_style))
    
    model_table_data = [
        [
            Paragraph("Algorithm Classifier", table_header_style), 
            Paragraph("Inference Decision", table_header_style), 
            Paragraph("Raw Pos Class Prob", table_header_style), 
            Paragraph("Decision Confidence", table_header_style)
        ]
    ]
    
    for name in model_predictions.keys():
        pred_label = "Heart Disease" if model_predictions[name] == 1 else "Healthy"
        prob = model_probabilities[name]
        conf = model_confidences[name]
        
        model_table_data.append([
            Paragraph(name, table_cell_style),
            Paragraph(pred_label, table_cell_bold_style if model_predictions[name] == 1 else table_cell_style),
            Paragraph(f"{prob:.4f}", table_cell_style),
            Paragraph(f"{conf*100:.2f}%", table_cell_style)
        ])
        
    t_models = Table(model_table_data, colWidths=[160, 120, 126, 126])
    t_models.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1a365d')),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 5),
        ('TOPPADDING', (0,0), (-1,-1), 5),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor('#f7fafc')]),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
    ]))
    story.append(t_models)
    story.append(Spacer(1, 10))
    
    # Consensus text
    neg_votes = total_votes - pos_votes
    agreement_pct = (max(pos_votes, neg_votes) / total_votes) * 100 if total_votes > 0 else 0.0
    c_status = "POSITIVE" if pos_votes >= 3 else ("INCONCLUSIVE TIE" if pos_votes == 2 else "NEGATIVE")
    story.append(Paragraph(
        f"<b>Consensus Inference Decision Summary</b>: Collective vote score of <b>{pos_votes}/{total_votes} positive votes</b> "
        f"yields a final ensemble result of <b>{ensemble_label.upper()}</b> ({agreement_pct:.0f}% agreement consensus).", 
        body_style
    ))
    story.append(Spacer(1, 12))
    
    # -------------------- 3. RISK ASSESSMENT --------------------
    story.append(Paragraph("3. Clinical Patient Risk Assessment", h1_style))
    
    risk_bg = '#fed6e3' if risk_category == 'HIGH RISK' else ('#fff9db' if risk_category == 'MEDIUM RISK' else '#e3fafc')
    risk_border = '#ff6b6b' if risk_category == 'HIGH RISK' else ('#fcc419' if risk_category == 'MEDIUM RISK' else '#51cf66')
    risk_txt_color = '#c92a2a' if risk_category == 'HIGH RISK' else ('#d9480f' if risk_category == 'MEDIUM RISK' else '#0b7285')
    
    t_risk_box = Table([[
        Paragraph(
            f"<font color='{risk_txt_color}'><b>ENSEMBLE RISK SCORE: {risk_score:.1f}% ({risk_category})</b></font><br/>"
            f"<font size='8.5' color='#495057'>{risk_desc}</font>",
            body_style
        )
    ]], colWidths=[532])
    t_risk_box.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor(risk_bg)),
        ('LEFTPADDING', (0,0), (-1,-1), 15),
        ('RIGHTPADDING', (0,0), (-1,-1), 15),
        ('TOPPADDING', (0,0), (-1,-1), 10),
        ('BOTTOMPADDING', (0,0), (-1,-1), 10),
        ('BOX', (0,0), (-1,-1), 1.5, colors.HexColor(risk_border)),
    ]))
    story.append(t_risk_box)
    story.append(Spacer(1, 15))
    
    # -------------------- 4. EXPLAINABLE AI (XAI) SUMMARY --------------------
    # Wrap XAI in KeepTogether to ensure it doesn't break poorly across pages
    xai_elements = [
        Paragraph("4. Custom Explainable AI (XAI) Summary", h1_style)
    ]
    
    # A) Linear Feature Contributions (Logistic Regression)
    xai_elements.append(Paragraph("<b>Logistic Regression Feature Contributions</b>", ParagraphStyle('SubSection', parent=body_bold_style, fontSize=9.5, spaceBefore=4, spaceAfter=4)))
    
    # Print risk-increasing and decreasing tables
    lr_data = [[
        Paragraph("Clinical Attribute", table_header_style), 
        Paragraph("Patient Entry Value", table_header_style),
        Paragraph("Logistic Coefficient Weight", table_header_style), 
        Paragraph("Patient Risk Influence Score", table_header_style)
    ]]
    
    # Add top increasing features (positive contribution)
    if df_pos is not None and not df_pos.empty:
        for _, row in df_pos.iterrows():
            lr_data.append([
                Paragraph(row['Feature'], table_cell_style),
                Paragraph(f"{row['Patient Value']:.1f}", table_cell_style),
                Paragraph(f"{row['Coefficient']:.4f}", table_cell_style),
                Paragraph(f"<font color='red'>+{row['Contribution']:.4f}</font>", table_cell_style)
            ])
            
    # Add decreasing features (negative contribution)
    if df_neg is not None and not df_neg.empty:
        for _, row in df_neg.iterrows():
            lr_data.append([
                Paragraph(row['Feature'], table_cell_style),
                Paragraph(f"{row['Patient Value']:.1f}", table_cell_style),
                Paragraph(f"{row['Coefficient']:.4f}", table_cell_style),
                Paragraph(f"<font color='green'>{row['Contribution']:.4f}</font>", table_cell_style)
            ])
            
    t_lr_contrib = Table(lr_data, colWidths=[180, 100, 126, 126])
    t_lr_contrib.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#2b6cb0')),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ('TOPPADDING', (0,0), (-1,-1), 4),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor('#f7fafc')]),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
    ]))
    xai_elements.append(t_lr_contrib)
    xai_elements.append(Spacer(1, 8))
    
    # B) Decision Tree Path Reasoning
    xai_elements.append(Paragraph("<b>Decision Tree Sequential Node Splits Traversed</b>", ParagraphStyle('SubSection2', parent=body_bold_style, fontSize=9.5, spaceBefore=4, spaceAfter=4)))
    
    if rules:
        dt_text = "Patient matched splits sequentially: " + "; ".join(rules[:5])
        if len(rules) > 5:
            dt_text += f" (+ {len(rules)-5} more node splits)"
        xai_elements.append(Paragraph(dt_text, ParagraphStyle('DtText', parent=body_style, fontSize=8.5, leading=11)))
    else:
        xai_elements.append(Paragraph("Decision Tree split criteria was not traced.", body_style))
        
    xai_elements.append(Spacer(1, 10))
    story.append(KeepTogether(xai_elements))
    
    # -------------------- 5. CLINICAL WARNINGS & RECOMMENDATIONS --------------------
    rec_elements = [
        Paragraph("5. Clinical Decision Warnings & Action Guidelines", h1_style)
    ]
    
    # Dynamic clinical warnings
    if warnings:
        warn_text = "<b>High-Risk Physiological Warnings Detected:</b><br/>"
        for w in warnings:
            # strip off markdown bold symbols
            clean_w = w.replace("**", "").replace("⚠️", "")
            warn_text += f"- {clean_w}<br/>"
        t_warnings_box = Table([[
            Paragraph(f"<font color='#c92a2a'>{warn_text}</font>", ParagraphStyle('WarnTxtStyle', parent=body_style, fontSize=8.5, leading=12))
        ]], colWidths=[532])
        t_warnings_box.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#fff5f5')),
            ('LEFTPADDING', (0,0), (-1,-1), 12),
            ('RIGHTPADDING', (0,0), (-1,-1), 12),
            ('TOPPADDING', (0,0), (-1,-1), 8),
            ('BOTTOMPADDING', (0,0), (-1,-1), 8),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#ffc9c9')),
        ]))
        rec_elements.append(t_warnings_box)
        rec_elements.append(Spacer(1, 8))
        
    # Recommendations Action Plan
    rec_text = "<b>Recommended Medical Action Guidelines:</b><br/>"
    for r in recs:
        clean_r = r.replace("**", "").replace("🏃", "").replace("🥗", "").replace("🩺", "").replace("🚨", "").replace("📋", "").replace("💊", "").replace("🗓️", "").replace("🔄", "").replace("📊", "").replace("⚖️", "")
        rec_text += f"- {clean_r}<br/>"
    t_recs_box = Table([[
        Paragraph(rec_text, ParagraphStyle('RecTxtStyle', parent=body_style, fontSize=8.5, leading=12))
    ]], colWidths=[532])
    t_recs_box.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f8f9fa')),
        ('LEFTPADDING', (0,0), (-1,-1), 12),
        ('RIGHTPADDING', (0,0), (-1,-1), 12),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#e9ecef')),
    ]))
    rec_elements.append(t_recs_box)
    
    # Disclaimer
    rec_elements.append(Spacer(1, 10))
    rec_elements.append(Paragraph(
        "<i>Disclaimer: This document is generated dynamically by an explainable AI clinical decision support tool "
        "and is intended solely for educational, analysis, and diagnostic reference. It does not replace the professional "
        "medical examination, advice, or intervention of a licensed cardiologist.</i>",
        ParagraphStyle('DisclaimerStyle', parent=body_style, fontSize=7.5, leading=10, textColor=colors.HexColor('#718096'))
    ))
    
    story.append(KeepTogether(rec_elements))
    
    # Build document
    doc.build(story, canvasmaker=NumberedCanvas)
    
    pdf_data = buffer.getvalue()
    buffer.close()
    
    return pdf_data
